<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var bool $canEdit
 * @var bool $isEditable
 * @var string $space "default" or "guest"
 *
 * @deprecated
 */

// Kept for old themes.

echo $this->partial('common/contribution-link');
