<?php

namespace DoctrineProxies\__CG__\Contribute\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContributionFile extends \Contribute\Entity\ContributionFile implements \Doctrine\Common\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'contribution', 'store', 'sourceName', 'size', 'sha256', 'created'];
        }

        return ['__isInitialized__', 'id', 'contribution', 'store', 'sourceName', 'size', 'sha256', 'created'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContributionFile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContribution(\Contribute\Entity\Contribution $contribution): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContribution', [$contribution]);

        return parent::setContribution($contribution);
    }

    /**
     * {@inheritDoc}
     */
    public function getContribution(): \Contribute\Entity\Contribution
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContribution', []);

        return parent::getContribution();
    }

    /**
     * {@inheritDoc}
     */
    public function setStore(string $store): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStore', [$store]);

        return parent::setStore($store);
    }

    /**
     * {@inheritDoc}
     */
    public function getStore(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStore', []);

        return parent::getStore();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourceName(?string $sourceName): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourceName', [$sourceName]);

        return parent::setSourceName($sourceName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceName', []);

        return parent::getSourceName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize(?int $size): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSha256(?string $sha256): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSha256', [$sha256]);

        return parent::setSha256($sha256);
    }

    /**
     * {@inheritDoc}
     */
    public function getSha256(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSha256', []);

        return parent::getSha256();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTime $created): \Contribute\Entity\ContributionFile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

}
