<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Form\ResourceForm $form
 * @var array $fields
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'edit items' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="container">
    <h2><?= $translate('New resource') ?></h2>
    <?= $this->pageTitle(sprintf($translate('Add %s'), $translate($mapLabels['items'])), 3) ?>
    <div class="messages">
        <p><?= $this->messages() ?></p>
    </div>
    <?php if (count($fields)): ?>
        <?php
        $this->trigger('view.edit.before');
        echo $partial('contribute/site/contribution/form', [
            'site' => $site,
            'form' => $form,
            'resource' => null,
            'contribution' => null,
            'fields' => $fields,
            'action' => 'add',
            'submitLabel' => $translate('Submit'),
        ]);
        $this->trigger('view.edit.after');
    elseif ($form): // First step form to select a resource template.
        $form->prepare()->init();
        $form->get('submit')->setValue('Select'); // @translate
        echo $this->form($form);
    else: ?>
    <div class="messages">
        <p><?= $translate('A template with fields is required to add a resource. Ask the administrator for more information.') ?></p>
    </div>
    <?php endif; ?>
</div>
