<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Omeka\Entity\User $user
 * @var \Contribute\Form\ContributeForm $form
 * @var array $fields
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $mode "read" (for template) or "write"
 * @var string $space "default" or "guest"
 */

// Resource/contribution is passed only when reading for template.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$contributionForm = $plugins->get('contributionForm');

$this->htmlElement('body')->appendAttribute('class', 'edit items ' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="contribute-resource conbribute-add container <?= $space && $space !== 'default' ? $space : '' ?>">">

    <?= $this->pageTitle(sprintf($translate('Add %s'), $translate($mapLabels['items'])), 2) ?>
    <h3><?= $escape($translate('New resource')) ?></h3>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php if (count($fields)):
        // The two lists of fields are merged in one form by default.
        $this->trigger('view.add.before');
        echo $contributionForm([
            'site' => $site,
            'contribution' => null,
            'resource' => null,
            'form' => $form,
            'fields' => $fields,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => 'add',
            'mode' => $mode,
            'space' => $space,
            'submitLabel' => $translate('Add'),
            'cancelLabel' => $translate('Cancel'),
            'isMainForm' => true,
            'skipContributeCss' => false,
        ]);
        $this->trigger('view.add.after');

    elseif ($form): // First step form to select a resource template.
        $form->prepare();
        if ($mode === 'read') {
            $form->remove('submit');
            echo $this->form($form);
        } else {
            $form->get('submit')->setValue('Select'); // @translate
            echo $this->form($form);
        }

    else: ?>
    <div class="messages">
        <p><?= $escape($translate('A template with fields is required to add a resource. Ask the administrator for more information.')) ?></p>
    </div>

    <?php endif; ?>

</div>
