<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'edit items' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="container">
    <h2><?= $resource->displayTitle() ?></h2>
    <?= $this->pageTitle(sprintf($translate('Edit %s'), $translate($mapLabels[$resource->resourceName()])), 3) ?>
    <div class="messages">
        <p><?= $this->messages() ?></p>
    </div>
    <?php if (count($fields) && $form): ?>
        <?php
        $this->trigger('view.edit.before');
        echo $partial('contribute/site/contribution/form', [
            'site' => $site,
            'form' => $form,
            'resource' => $resource,
            'contribution' => $contribution,
            'fields' => $fields,
            'action' => 'edit',
            'submitLabel' => $translate('Submit'),
        ]);
        $this->trigger('view.edit.after');
    else: ?>
        <div class="messages">
            <p><?= $translate('A template with fields is required to edit this resource. Ask the administrator for more information.') ?></p>
        </div>
    <?php endif; ?>
</div>
