<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Omeka\Entity\User $user
 * @var \Contribute\Form\ContributeForm $form
 * @var array $fields
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $mode "read" (for show readonly form before submit) or "write"
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'edit items ' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="contribute-resource conbribute-edit container">

    <?= $this->pageTitle($resource ? $escape($resource->displayTitle()) : $translate('New contribution'), 2) ?>
    <h3><?= $resource ? sprintf($translate('Edit %s'), $translate($mapLabels[$resource->resourceName()])) : $translate('Edit contribution') ?></h3>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php if (count($fields) && $form):
        // The two lists of fields are merged in one form by default.
        $this->trigger('view.edit.before');
        echo $partial('contribute/site/contribution/form', [
            'site' => $site,
            'contribution' => $contribution,
            'resource' => $resource,
            'form' => $form,
            'fields' => $fields,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => 'edit',
            'mode' => $mode,
            'submitLabel' => $translate('Submit'),
            'isMainForm' => true,
            'skipContributeCss' => false,
        ]);
        $this->trigger('view.edit.after');
    else: ?>
    <div class="messages">
        <p><?= $translate('A template with fields is required to edit this resource. Ask the administrator for more information.') ?></p>
    </div>
    <?php endif; ?>

</div>
