<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

// Don't prepare form if there are no fields.
if (count($fields)) {
    $this->headLink()
        ->appendStylesheet($assetUrl('vendor/chosen-js/chosen.css', 'Omeka'))
        ->appendStylesheet($assetUrl('css/contribute.css', 'Contribute'));
    $this->headScript()
        ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
        ->appendFile($assetUrl('js/contribute.js', 'Contribute'), 'text/javascript', ['defer' => 'defer']);

    // To check if ValueSuggest is available, just try to get the routed url.
    try {
        $proxyUrl = $this->url('admin/value-suggest/proxy', [], true);
        $this->headLink()
            ->appendStylesheet($assetUrl('css/valuesuggest.css', 'Contribute'));
        $this->headScript()
            ->appendFile($assetUrl('vendor/jquery-autocomplete/jquery.autocomplete.min.js', 'AdvancedResourceTemplate'), 'text/javascript', ['defer' => 'defer'])
            ->appendFile($assetUrl('js/valuesuggest.js', 'Contribute'), 'text/javascript', ['defer' => 'defer'])
            ->appendScript(sprintf(
                'const valueSuggestProxyUrl = "%s";',
                $this->escapeJs($proxyUrl)
            ));
    } catch (\Exception $e) {
        // Nothing to prepare.
    }
}

$this->htmlElement('body')->appendAttribute('class', 'edit items' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="container">
    <h2><?= $resource->displayTitle() ?></h2>
    <?= $this->pageTitle(sprintf($translate('Edit %s'), $translate($mapLabels[$resource->resourceName()])), 3) ?>
    <div class="messages">
        <p><?= $this->messages() ?></p>
    </div>
    <?php if (count($fields) && $form): ?>
        <?php
        $this->trigger('view.edit.before');
        echo $this->partial('contribute/site/contribution/form', [
            'site' => $site,
            'form' => $form,
            'resource' => $resource,
            'contribution' => $contribution,
            'fields' => $fields,
            'action' => 'edit',
            'submitLabel' => $translate('Submit'),
        ]);
        $this->trigger('view.edit.after');
    else: ?>
        <div class="messages">
            <p><?= $translate('A template with fields is required to edit this resource. Ask the administrator for more information.') ?></p>
        </div>
    <?php endif; ?>
</div>
