<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 *
 * @var \Laminas\View\Helper\Partial $partial
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 * @var bool $hasNumericDataTypes
 * @var ?array $customVocabBaseTypes
 *
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var ?\Omeka\Api\Representation\ValueRepresentation $value
 * @var ?array $fieldContribution
 * @var ?int $indexContribution
 */

$original = $fieldContribution['original'];
$proposed = $fieldContribution['proposed'];
$isPrivate = $value ? !$value->isPublic() : (empty($field['template_property']) ? false : $field['template_property']->isPrivate());
$isRequired = $fieldContribution && !empty($fieldContribution['required']) && (($indexContribution ?? null) === 0);

$val = $proposed['@resource'] ?? $original['@resource'] ?? '';

$class = ['value'];
if ($isPrivate):
    $class[] = 'private';
endif;
$language = isset($proposed['@value']) ? null : (isset($original['value']) ? $original['value']->lang() : null);
?>

<div class="<?= implode(' ', $class) ?>" lang="<?= $escape($language) ?>">
    <div class="value resource<?= $isPrivate ? ' private' : '' ?>">
        <?php if ($isPrivate): ?>
        <span class="private fa fa-eye-slash" aria-hidden="false" title="<?= $translate('private') ?>"></span>
        <?php endif;

        // Display the value when no query is set.
        if (!isset($valueResourceQueries[$term])): ?>
        <?= $value ? $value->asHtml() : $proposed['@value'] ?>
        <?php else:
            // TODO Manage all resource types. Currently, items is forced when not set.
            $resourceValue = $value ? $value->valueResource() : null;
            $val = $proposed['@resource'] ?? $original['@resource'];
            $resourceName = $valueResourceTypes[$fieldContribution['type']] ?? 'items';
            $element = new \Omeka\Form\Element\ResourceSelect($term . '[' . $indexFieldInput . '][@resource]');
            $element
                ->setApiManager($apiManager);
            $element
                ->setResourceValueOptions($resourceName, $shortResourceTitle, $valueResourceQueries[$term]);
            $valueOptions = $element->getValueOptions();
            if ($resourceValue && !isset($valueOptions[$resourceValue->id()])):
                $element
                    ->setOption('prepend_value_options', [$resourceValue->id() => mb_substr($resourceValue->displayTitle(), 0, 80)])
                    ->setResourceValueOptions($resourceName, $shortResourceTitle, $valueResourceQueries[$term]);
            endif;
            $element
                ->setEmptyOption('')
                ->setAttributes([
                    'class' => 'form-control input-value chosen-select',
                    'required' => $isRequired,
                    'multiple' => false,
                    'data-value-key' => '@resource',
                    'aria-labelledby' => 'property-' . $property->id() . '-label',
                    'data-placeholder' => $translate('Select a resource…'),
                    'value' => $val,
                ]);
            echo $this->formElement($element);
        endif; ?>
    </div>
</div>
