<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Contribute\Form\ContributeForm $form
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 *
 * @var string $submitLabel
 * @var string $cancelLabel
 * @var bool $isMainForm
 * @var bool $skipContributeCss
 *
 * When called recursively for sub-fields (media):
 * @var ?int $indexMedia
 * @var array $fieldsMedia
 *
 * @var \Laminas\View\HelperPluginManager $plugins
 * @var \Laminas\View\Helper\Url $url
 * @var \Laminas\View\Helper\Partial $partial
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var \Common\Stdlib\EasyMeta $easyMeta
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 * @var string $baseUrlFiles
 * @var string $mode
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var ?\Omeka\Api\Representation\ResourceTemplatePropertyRepresentation $templateProperty
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var \Omeka\Api\Representation\ValueRepresentation $value
 */

// TODO Hide button when the number of values is >= max values (currently on load in js); display it when no values and not fillable. So count values before in form or via the current field. And manage required at least one.

$addForMedia = $isMainForm ? '' : ' add-value-media';
?>

<div class="inputs">
    <div class="add-values default-selector" data-next-index="<?= $indexFieldInput ?>" data-next-term="<?= $term ?>"<?php /* if (empty($field['fillable'])): ?> style="display: none;"<?php endif; */?>>
        <?php foreach ($field['datatypes'] as $dataType) switch($dataType):

            case 'literal':
            ?>
        <button type="button" class="add-value add-value-literal<?= $addForMedia ?> button o-icon-add"><?= $escape($translate('Add value')) ?></button>
                <?php
                break;

            case 'numeric:integer':
                ?>
        <button type="button" class="add-value add-value-numeric-integer<?= $addForMedia ?> button o-icon-add"><?= $escape($translate('Add number')) ?></button>
                <?php
                break;

            case 'numeric:timestamp':
                ?>
        <button type="button" class="add-value add-value-numeric-timestamp<?= $addForMedia ?> button o-icon-add"><?= $escape($translate('Add date')) ?></button>
                <?php
                break;

            case 'resource':
            case 'resource:item':
            case 'resource:itemset':
            case 'resource:media':
                if (isset($valueResourceQueries[$term])):
                    // Get the list of options from the core select element.
                    $resourceName = $valueResourceTypes[$dataType];
                    $element = new \Omeka\Form\Element\ResourceSelect();
                    $element
                        ->setApiManager($apiManager);
                    $element
                        ->setResourceValueOptions($resourceName, $shortResourceTitle, $valueResourceQueries[$term]);
                    // The order should be kept, but there is no order in a js array.
                    $valueOptions = [];
                    foreach ($element->getValueOptions() as $k => $v) {
                        $valueOptions[] = ['v' => $k, 't' => $v];
                    }
                ?>
        <button type="button" class="add-value add-value-resource<?= $addForMedia ?> button o-icon-uri" data-data-type="<?= $dataType ?>" data-placeholder="<?= $translate('Select a resource…')?>" data-value-options="<?= $escapeAttr(json_encode($valueOptions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) ?>"><?= $escape($translate('Add linked resource')) ?></button>
                <?php endif;
                break;

            case 'uri':
                ?>
        <button type="button" class="add-value add-value-uri<?= $addForMedia ?> button o-icon-uri" data-data-type="uri"><?= $escape($translate('Add URI')) ?></button>
                <?php break;

            case substr($dataType, 0, 12) === 'customvocab:':
                /** @var \CustomVocab\Api\Representation\CustomVocabRepresentation $customVocab */
                $customVocab = $apiManager->read('custom_vocabs', ['id' => substr($dataType, 12)])->getContent();
                $mainType = $easyMeta->dataTypeMainCustomVocab($dataType) ?: 'literal';
                $valueOptions = [
                    // Managed via js.
                    // ['v' => '', 't' => $translate('Select a value')],
                ];
                // Manage hierarchical list (via module Thesaurus).
                $isCustomVocabThesaurus = $customVocab && $mainType === 'resource' && $plugins->has('thesaurus') && ($itemSet = $customVocab->itemSet()) && ($itemSetClass = $itemSet->resourceClass()) && in_array($itemSetClass->term(), ['skos:Collection', 'skos:OrderedCollection']);
                if ($isCustomVocabThesaurus) {
                    $result = $plugins->get('thesaurus')($itemSet)->listTree(['indent' => '– ']);
                } else {
                    $result = $customVocab->listValues();
                }
                foreach ($result as $term => $value) {
                    $valueOptions[] = ['v' => $value, 't' => $term];
                }
                ?>
        <button type="button" class="add-value add-value-custom-vocab<?= $addForMedia ?> button o-icon-add" data-data-type="<?= $dataType ?>" data-basetype="<?= $mainType ?>" data-value-options="<?= $escapeAttr(json_encode($valueOptions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) ?>" data-placeholder="<?= $escapeAttr($translate('Select a value…')) ?>"><?= $escape($translate('Add value')) ?></button>
                <?php break;

            case substr($dataType, 0, 12) === 'valuesuggest': // Or valuesuggestall.
                ?>
        <button type="button" class="add-value add-value-value-suggest<?= $addForMedia ?> button o-icon-uri" data-data-type="<?= $dataType ?>"><?= $escape($translate('Add linked data')) ?></button>
                <?php break;

            default:
                // TODO Other types are not managed.
        endswitch; ?>
    </div>
</div>
