<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 *
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 * @var ?array $customVocabBaseTypes
 *
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 */

// Templates for the fields according to the datatype.
// They are outside the template form and marked readonly to not be included in the form.
?>

<div id="edit_value_template" class="contribute_template value" style="display:none;">
    <div class="value" lang="">
        <textarea class="form-control input-value" data-value-key="@value" name="dcterms:title[__INDEX__][@value]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"></textarea>
    </div>
</div>

<div id="edit_resource_template" class="contribute_template resource" style="display:none;">
    <div class="value resource">
        <select class="form-control input-value" data-value-key="@resource" name="dcterms:title[__INDEX__][@resource]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
</div>

<div id="edit_uri_template" class="contribute_template uri" style="display:none;">
    <div class="value" data-data-type="uri" role="group">
        <div class="input-body">
            <div class="input">
                <label class="value input-container">
                    <?= $translate('URI') ?>:
                    <input type="text" class="form-control value" data-value-key="@uri" name="dcterms:title[__INDEX__][@uri]" readonly="readonly"/>
                </label>
            </div>
            <div class="input">
                <label class="value-label label-container">
                    <?= $translate('Label') ?>:
                    <input type="text" class="form-control value-label" data-value-key="@label" name="dcterms:title[__INDEX__][@label]" readonly="readonly"/>
                </label>
            </div>
        </div>
    </div>
</div>

<?php if (!empty($customVocabBaseTypes)): ?>
<div id="edit_customvocab_template" class="contribute_template custom_vocab" style="display:none;">
    <div class="value custom_vocab" data-basetype="literal">
        <select class="form-control input-value" data-value-key="@value" name="dcterms:title[__INDEX__][@value]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
    <div class="value custom_vocab" data-basetype="resource">
        <select class="form-control input-value" data-value-key="@resource" name="dcterms:title[__INDEX__][@resource]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
    <div class="value custom_vocab" data-basetype="uri">
        <select class="form-control input-value" data-value-key="@uri" name="dcterms:title[__INDEX__][@uri]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
</div>
<?php endif; ?>

<?php if ($hasValueSuggest): ?>
<div id="edit_valuesuggest_template" class="contribute_template value_suggest" style="display:none;">
    <div class="value value_suggest">
        <input type="text" class="form-control valuesuggest-input" data-value-key="@uri" name="dcterms:title[__INDEX__][@uri]" data-data-type="" data-uri="" data-value="" value="" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"/>
    </div>
</div>
<?php endif; ?>
