<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 *
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 * @var ?array $customVocabSubTypes
 *
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var \Omeka\Api\Representation\ValueRepresentation $value
 */

?>

<div class="inputs">
    <div class="add-values default-selector" data-next-index="<?= $indexFieldInput ?>" data-next-term="<?= $term ?>">
        <?php foreach ($field['datatypes'] as $datatype) switch($datatype):

            case 'literal': ?>
        <div class="add-value add-value-new button o-icon-add"><?= $translate('Add value') ?></div>
            <?php
                break;

            case 'resource':
            case 'resource:item':
            case 'resource:itemset':
            case 'resource:media':
                if (isset($valueResourceQueries[$term])):
                    // Get the list of options from the core select element.
                    $resourceName = $valueResourceTypes[$datatype];
                    $element = new \Omeka\Form\Element\ResourceSelect();
                    $element
                        ->setApiManager($apiManager);
                    $element
                        ->setResourceValueOptions($resourceName, $shortResourceTitle, $valueResourceQueries[$term]);
                    // The order should be kept, but there is no order in a js array.
                    $valueOptions = [];
                    foreach ($element->getValueOptions() as $k => $v) {
                        $valueOptions[] = ['v' => $k, 't' => $v];
                    }
                ?>
        <div class="add-value add-value-resource button o-icon-uri" data-type="<?= $datatype ?>" data-placeholder="<?= $translate('Select a resource…')?>" data-value-options="<?= $escapeAttr(json_encode($valueOptions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) ?>"><?= $translate('Add linked resource') ?></div>
                <?php endif;
                break;

            case 'uri': ?>
        <div class="add-value add-value-uri button o-icon-uri" data-type="uri"><?= $translate('Add URI') ?></div>
                <?php break;

            case substr($datatype, 0, 12) === 'customvocab:':
                // @see \CustomVocab\DataType\CustomVocab
                $subType = $customVocabSubTypes[substr($datatype, 12)] ?? 'literal';
                $customVocab = $apiManager->read('custom_vocabs', ['id' => substr($datatype, 12)])->getContent();
                $valueOptions = [];
                if ($subType === 'resource') {
                    $result = $apiManager->search('items', ['item_set_id' => $customVocab->itemSet()->id(), 'sort_by' => 'title'], ['initialize' => false, 'returnScalar' => 'title'])->getContent();
                    foreach ($result as $id => $title) {
                        $valueOptions[] = ['v' => $id, 't' => $title];
                    }
                } elseif ($subType === 'uri') {
                    $matches = [];
                    $uris = array_map('trim', preg_split("/\r\n|\n|\r/", $customVocab->uris()));
                    foreach ($uris as $uri) {
                        if (preg_match('/^(\S+) (.+)$/', $uri, $matches)) {
                            $valueOptions[] = ['v' => $matches[1], 't' => $matches[2]];
                        } elseif (preg_match('/^(.+)/', $uri, $matches)) {
                            $valueOptions[] = ['v' => $matches[1], 't' => $matches[1]];
                        }
                    }
                } else {
                    $terms = array_map('trim', preg_split("/\r\n|\n|\r/", $customVocab->terms()));
                    foreach ($terms as $term) {
                        $valueOptions[] = ['v' => $term, 't' => $term];
                    }
                }
                ?>
        <div class="add-value add-value-custom-vocab button o-icon-add" data-type="<?= $datatype ?>" data-subtype="<?= $subType ?>" data-value-options="<?= $escapeAttr(json_encode($valueOptions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) ?>"><?= $translate('Add value') ?></div>
                <?php break;

            case substr($datatype, 0, 12) === 'valuesuggest': // Or valuesuggestall. ?>
        <div class="add-value add-value-value-suggest button o-icon-uri" data-type="<?= $datatype ?>"><?= $translate('Add linked data') ?></div>
                <?php break;

            default:
                // TODO Other types are not managed.
        endswitch; ?>
        <div class="clearfix"></div>
    </div>
</div>
