<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 *
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 *
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var ?\Omeka\Api\Representation\ValueRepresentation $value
 * @var array $fieldContribution
 */

$original = $fieldContribution['original'];
$proposed = $fieldContribution['proposed'];
$isPrivate = $value ? !$value->isPublic() : ($field['template_property'] ? $field['template_property']->isPrivate() : false);

$val = $proposed['@uri'] ?? $original['@uri'];
$label = $proposed['@uri'] ?? $original['@label'];

$class = ['value'];
$class[] = 'uri';
if ($isPrivate):
    $class[] = 'private';
endif;
$language = isset($proposed['@value']) ? null : (isset($original['value']) ? $original['value']->lang() : null);
?>

<div class="<?= implode(' ', $class) ?>" lang="<?= $escape($language) ?>" data-data-type="uri" role="group">
    <div class="input-body">
        <div class="input">
            <label class="value input-container">
                <?= $translate('URI') ?>:
                <input type="text" class="form-control value to-require" data-value-key="@id" name="<?= $term . '[' . $indexFieldInput . '][@uri]' ?> " value = "<?= $escapeAttr($val) ?>"/>
            </label>
        </div>
        <div class="input">
            <label class="value-label label-container">
                <?= $translate('Label') ?>:
                <textarea class="form-control value-label" rows="1" data-value-key="o:label" name="<?= $term . '[' . $indexFieldInput . '][@label]' ?>"><?= $escape($label) ?></textarea>
            </label>
        </div>
    </div>
</div>
