<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Contribute\Form\ContributeForm $form
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 *
 * @var string $submitLabel
 * @var string $cancelLabel
 * @var bool $isMainForm
 * @var bool $skipContributeCss
 *
 * When called recursively for sub-fields (media):
 * @var ?int $indexMedia
 * @var array $fieldsMedia
 *
 * @var \Laminas\View\Helper\Url $url
 * @var \Laminas\View\Helper\Partial $partial
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var ?array $customVocabBaseTypes
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 * @var string $baseUrlFiles
 * @var string $mode
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var ?\Omeka\Api\Representation\ResourceTemplatePropertyRepresentation $templateProperty
 * @var ?\Omeka\Api\Representation\PropertyRepresentation $property
 * @var ?\Omeka\Api\Representation\ValueRepresentation $value
 * @var ?array $fieldContribution
 * @var ?int $indexContribution
 * @var bool $readonly
 */

$original = $fieldContribution['original'];
$proposed = $fieldContribution['proposed'];
$isPrivate = $value ? !$value->isPublic() : (isset($templateProperty) ? $templateProperty->isPrivate() : false);
$isRequired = !empty($field['required']) && (($indexContribution ?? null) === 0);

$propertyId = $property ? $property->id() : '__PROPERTYID__';
$baseName = $isMainForm
    ? sprintf('%s[%s]', $term, $indexFieldInput)
    : sprintf('media[%s][%s][%s]', $indexMedia, $term, $indexFieldInput);

$val = $proposed['@value'] ?? $original['@value'] ?? '';

$class = ['value', 'group-input-part'];
if ($isPrivate):
    $class[] = 'private';
endif;

[$year, $month, $day] = explode('-', $val . '--', 3);
$year = trim((string) $year, '- ');
$month = trim((string) $month, '- ');
$day = trim((string) $day, '- ');
?>

<?php
// Use a pseudo-hidden "tel" to validate via the form directly and reduce issues.
// The pattern is only for date for now, not full time.
// The year/month/date is filled via js (name and value).
// TODO The main input is hidden via css and not set required to avoid issue with js.
?>
<div class="<?= implode(' ', $class) ?>" role="group">
    <input style="display:none;" type="tel" data-input-part="main" data-value-key="@value" name="<?= $baseName . '[@value]' ?>" aria-labelledby="property-<?= $propertyId ?>-label" <?= empty($readonly) ? '' : ' readonly="readonly"' ?> value="<?= $escapeAttr($val) ?>" pattern="^\d{4}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2\d)|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))$" />
    <div class="input-body">
        <div class="input">
            <label class="value input-container">
                <?= $translate('Year') ?>
                <input type="tel" pattern="^\d{4}$" class="form-control input-value" data-input-part="year" name="<?= $baseName . '[year]' ?>" aria-labelledby="property-<?= $propertyId ?>-label" <?= $isRequired ? ' required="required"' : '' ?><?= empty($readonly) ? '' : ' readonly="readonly"' ?> value="<?= $escapeAttr($year) ?>"/>
            </label>
        </div>
        <div class="input">
            <label class="value input-container">
                <?= $translate('Month') ?>
                <input type="tel" pattern="^(?:0?[1-9]|1[0-2])$" class="form-control input-value" data-input-part="month" name="<?= $baseName . '[month]' ?>" aria-labelledby="property-<?= $propertyId ?>-label" <?= $isRequired ? ' required="required"' : '' ?><?= empty($readonly) ? '' : ' readonly="readonly"' ?> value="<?= $escapeAttr($month) ?>"/>
            </label>
        </div>
        <div class="input">
            <label class="value input-container">
                <?= $translate('Day') ?>
                <input type="tel" pattern="^(?:0?[1-9]|[1-2]\d|3[0-1])$" class="form-control input-value" data-input-part="day" name="<?= $baseName . '[day]' ?>" aria-labelledby="property-<?= $propertyId ?>-label" <?= $isRequired ? ' required="required"' : '' ?><?= empty($readonly) ? '' : ' readonly="readonly"' ?> value="<?= $escapeAttr($day) ?>"/>
            </label>
        </div>
    </div>
    <ul class="actions">
        <li><button type="button" class="o-icon-delete remove-value" title="<?= $escapeAttr($translate('Remove value')) ?>" href="#" aria-label="<?= $escapeAttr($translate('Remove value')) ?>"></button></li>
    </ul>
</div>
