<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 *
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 * @var bool $hasNumericDataTypes
 * @var ?array $customVocabBaseTypes
 *
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 *
 * @var array $field
 * @var string $term
 * @var int $indexFieldInput
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var ?\Omeka\Api\Representation\ValueRepresentation $value
 * @var ?array $fieldContribution
 * @var ?int $indexContribution
 */

$original = $fieldContribution['original'];
$proposed = $fieldContribution['proposed'];
$isPrivate = $value ? !$value->isPublic() : ($field['template_property'] ? $field['template_property']->isPrivate() : false);
$isRequired = !empty($fieldContribution['required']) && (($indexContribution ?? null) === 0);

$val = $proposed['@uri'] ?? $original['@uri'];
$label = isset($proposed['@uri']) ? $proposed['@label'] : $original['@label'];

$class = ['value', 'value-suggest'];
if ($isPrivate):
    $class[] = 'private';
endif;
$language = isset($proposed['@uri']) ? null : (isset($original['value']) ? $original['value']->lang() : null);
?>

<div class="<?= implode(' ', $class) ?>" lang="<?= $escape($language) ?>">
    <?php if ($language): ?>
    <span class="language"><?= $language ?></span>
    <?php endif; ?>
    <input type="text" class="form-control valuesuggest-input" data-value-key="@uri" name="<?= $term . '[' . $indexFieldInput . '][@uri]' ?>" data-data-type="<?= $escapeAttr($fieldContribution['type']) ?>" data-uri="<?= $escapeAttr($val) ?>" data-value="<?= $escapeAttr($label) ?>" value="<a href=&quot;<?= $escapeAttr($val) ?>&quot; target=&quot;_blank&quot;><?= $escapeAttr($label) ?></a>"<?= $isRequired ? ' required="required"' : '' ?>/>
</div>
