<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var array $fields
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 * @var bool $isMainForm
 * When called recursively for sub-fields (media):
 * @var ?int $indexMedia
 * @var array $fieldsMedia
 *
 * @var \Laminas\View\Helper\Partial $partial
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var \Omeka\Api\Manager $apiManager
 * @var bool $hasValueSuggest
 * @var bool $hasNumericDataTypes
 * @var ?array $customVocabBaseTypes
 * @var array $valueResourceTypes
 * @var array $valueResourceQueries
 * @var callable $shortResourceTitle
 * @var string $baseUrlFiles
 */

// Templates for the fields according to the datatype.
// They are outside the template form and marked readonly to not be included in the form.
// The names are updated through js, so don't need to check for main form or sub form.

$args = $this->vars()->getArrayCopy();
$args['field'] = ['template_property' => null];
$args['term'] = 'field-to-set';
$args['indexFieldInput'] = 0;
$args['property'] = null;
$args['value'] = null;
$args['fieldContribution'] = ['type' => null, 'required' => false, 'original' => [], 'proposed' => [], 'template_property' => null];
$args['indexContribution'] = null;
$args['readonly'] = true;
?>

<div id="edit_template_value" class="contribute_template value" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-literal', $args) ?>
</div>

<div id="edit_template_resource" class="contribute_template resource" style="display:none;">
    <div class="value resource">
        <select class="form-control input-value" data-value-key="@resource" name="dcterms:title[__INDEX__][@resource]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
</div>

<div id="edit_template_uri" class="contribute_template uri" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-uri', $args) ?>
</div>

<div id="edit_template_media-file" class="contribute_template media" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-media-file', $args) ?>
</div>

<?php if ($hasNumericDataTypes): ?>
<div id="edit_template_numeric-integer" class="contribute_template value" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-numeric-integer', $args) ?>
</div>
<div id="edit_template_numeric-timestamp" class="contribute_template value" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-numeric-timestamp', $args) ?>
</div>
<?php endif; ?>

<?php if (!empty($customVocabBaseTypes)): ?>
<div id="edit_template_customvocab" class="contribute_template custom_vocab" style="display:none;">
    <div class="value custom_vocab" data-basetype="literal">
        <select class="form-control input-value" data-value-key="@value" name="dcterms:title[__INDEX__][@value]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
    <div class="value custom_vocab" data-basetype="resource">
        <select class="form-control input-value" data-value-key="@resource" name="dcterms:title[__INDEX__][@resource]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
    <div class="value custom_vocab" data-basetype="uri">
        <select class="form-control input-value" data-value-key="@uri" name="dcterms:title[__INDEX__][@uri]" aria-labelledby="property-__PROPERTYID__-label" readonly="readonly"><option value=""></option></select>
    </div>
</div>
<?php endif; ?>

<?php if ($hasValueSuggest): ?>
<div id="edit_template_valuesuggest" class="contribute_template value_suggest" style="display:none;">
    <?= $partial('contribute/site/contribution/form-input-value-suggest', $args) ?>
</div>
<?php endif; ?>
