<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Contribute\Form\ContributeForm $form
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 *
 * @var string $submitLabel
 * @var string $cancelLabel
 * @var bool $isMainForm
 * @var bool $skipContributeCss
 */

// Prepare all the variables one time to simplify sub-template and sub-forms.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// The api manager is needed to create select for Value Suggest.
// TODO Replace apiManager by FormElementManager.
$services = $site->getServiceLocator();
$apiManager = $services->get('Omeka\ApiManager');
$customVocabBaseTypes = $plugins->get('customVocabBaseType')();

// Prepare resource selects.
$valueResourceTypes = ['resource' => 'items', 'resource:item' => 'items', 'resource:itemset' => 'item_sets', 'resource:media' => 'media'];
// TODO Use module advanced resource template to fill a property with a property query. They are always empty for now, except manually filled.
$valueResourceQueries = [];
$shortResourceTitle = function (\Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource): string {
    return mb_substr($resource->displayTitle(), 0, 80);
};

$baseUrlFiles = $services->get('Config')['file_store']['local']['base_uri'] ?: rtrim($url('top'), '/') . '/files';

$indexMedia = null;
$fieldsMedia = [];

// Use of a sub-form requires a main form, but the main form may be unavailable.
if (isset($form)) $form->prepare();

// Avoid to prepare many variables in sub-templates.
$vars = $this->vars()->getArrayCopy();
$vars['mode'] = isset($form) ? $mode : 'read';
$vars['indexMedia'] = $indexMedia;
$vars['fieldsMedia'] = $fieldsMedia;
$vars['url'] = $url;
$vars['partial'] = $partial;
$vars['escape'] = $escape;
$vars['translate'] = $translate;
$vars['escapeAttr'] = $escapeAttr;
$vars['apiManager'] = $apiManager;
$vars['customVocabBaseTypes'] = $customVocabBaseTypes;
$vars['valueResourceTypes'] = $valueResourceTypes;
$vars['valueResourceQueries'] = $valueResourceQueries;
$vars['shortResourceTitle'] = $shortResourceTitle;
$vars['baseUrlFiles'] = $baseUrlFiles;

$plugins
    ->get(\Laminas\View\Helper\ViewModel::class)
    ->getRoot()
    ->setVariable('contributeVars', $vars);

$assetUrl = $plugins->get('assetUrl');
$this->headLink()
    ->prependStylesheet($assetUrl('vendor/chosen-js/chosen.min.css', 'Omeka'));
if (empty($skipContributeCss)) {
    $this->headLink()
        ->appendStylesheet($assetUrl('css/contribute.css', 'Contribute'));
}
$this->headScript()
    ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.min.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/contribute.js', 'Contribute'), 'text/javascript', ['defer' => 'defer']);

$js = '';
// To check if ValueSuggest is available, just try to get the routed url.
try {
    $proxyUrl = $this->url('admin/value-suggest/proxy', [], true);
    $this->headLink()
        ->appendStylesheet($assetUrl('css/valuesuggest.css', 'Contribute'));
    $this->headScript()
        ->appendFile($assetUrl('vendor/jquery-autocomplete/jquery.autocomplete.min.js', 'AdvancedResourceTemplate'), 'text/javascript', ['defer' => 'defer'])
        ->appendFile($assetUrl('js/valuesuggest.js', 'Contribute'), 'text/javascript', ['defer' => 'defer']);
    $js .= sprintf('const valueSuggestProxyUrl = "%s";', $this->escapeJs($proxyUrl));
} catch (\Exception $e) {
    // Nothing to prepare.
}

// Store in js basic config of the fields.
$simpleFields = $fields ?? [];
foreach ($simpleFields as &$simpleField) {
    unset($simpleField['template_property'], $simpleField['property'], $simpleField['alternate_comment'], $simpleField['alternate_label'], $simpleField['values'], $simpleField['contributions']);
}
unset($simpleField);
$js .= PHP_EOL . sprintf('const fields = %s;', json_encode($simpleFields, 320));
$simpleMediaFields = $fieldsMediaBase ?? [];
foreach ($simpleMediaFields as &$simpleMediaField) {
    unset($simpleMediaField['template_property'], $simpleMediaField['property'], $simpleMediaField['alternate_comment'], $simpleMediaField['alternate_label'], $simpleMediaField['values'], $simpleMediaField['contributions']);
}
unset($simpleMediaField);
$js .= PHP_EOL . sprintf('const templateMedia = %s;', $templateMedia ? $templateMedia->id() : 'null');
$js .= PHP_EOL . sprintf('const mediaFields = %s;', json_encode($simpleMediaFields, 320));
$this->headScript()
    ->appendScript($js);
