<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation $contribution
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// $medias = $contributions->media();
$medias = [];
$embedMedia = $siteSetting('item_media_embed', false);

$filterLocale = (bool) $siteSetting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;

$this->htmlElement('body')->appendAttribute('class', 'contribution resource show');
?>

<script>
function contributionDelete(id){
    $.post({
        url: <?= json_encode(substr($url('site/contribution-id', ['action' => 'delete', 'resource' => 'contribution', 'id' => 0], true), 0, -8), 320) ?> + id + '/delete',
        data: {
            'id': id,
            'confirmform_csrf': <?= json_encode($site->getServiceLocator()->get('FormElementManager')->get(\Omeka\Form\ConfirmForm::class)->prepare()->get('confirmform_csrf')->getValue()) ?>,
        },
    });
}
</script>

<?= $this->pageTitle($contribution->displayTitle(null, $lang), 2); ?>
<h3><?= $translate('Contribution') ?></h3>

<div class="messages">
    <p><?= $this->messages() ?></p>
</div>

<?php $this->trigger('view.show.before'); ?>

<?php if ($embedMedia && $medias): ?>
    <div class="media-embeds">
    <?php foreach ($medias as $media): ?>
        <?= $media->render() ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

<?= $contribution->displayValues() ?>

<?php if (!$embedMedia && $medias): ?>
<div class="media-list">
    <?php foreach ($medias as $media): ?>
        <?= $media->linkPretty() ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<ul class="form-buttons">
    <?php if ($contribution->userIsAllowed('update')): ?>
    <li><a href="<?= $url('site/contribution-id', ['action' => 'edit', 'resource' => 'contribution', 'id' => $contribution->id()], true) ?>" class="form-button edit-button"><?= $translate('Edit') ?></a></li>
    <?php endif; ?>
    <?php if ($contribution->userIsAllowed('delete')): ?>
    <li><a href="<?= $url('site/contribution-id', ['action' => 'delete', 'resource' => 'contribution', 'id' => $contribution->id()], true) ?>" class="form-button delete-button" onclick="if (confirm(<?= $escapeAttr(json_encode($translate('Are you sure to remove this contribution?'))) ?>)) { contributionDelete(<?= $contribution->id() ?>); } else { return false; }"><?= $translate('Delete') ?></a></li>
    <?php endif; ?>
</ul>

<?php $this->trigger('view.show.after'); ?>
