<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation $contribution
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$medias = $contribution->valuesMedias();
$embedMedia = $siteSetting('item_media_embed', false);

$filterLocale = (bool) $siteSetting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;

$partial('contribute/site/contribution/asset-include');

$this->htmlElement('body')->appendAttribute('class', 'contribution resource show');
?>

<?= $this->pageTitle($contribution->displayTitle(null, $lang), 2); ?>
<h3><?= $translate('Contribution') ?></h3>

<ul class="contribution-status">
    <li class="contribution-resource"><?= $contribution->resource() ? $contribution->resource()->linkPretty() : $escape($translate('No resource')) ?></li>
    <li class="submitted"><?= $escape($resource->isSubmitted() ? $translate('Is submitted') : $translate('Is not submitted')) ?></li>
    <li class="reviewed"><?= $escape($resource->isReviewed() ? $translate('Is reviewed') : $translate('Is not reviewed')) ?></li>
</ul>

<div class="messages">
    <p><?= $this->messages() ?></p>
</div>

<?php $this->trigger('view.show.before'); ?>

<?php if ($embedMedia && $medias): ?>
    <div class="media-embeds">
    <?php foreach ($medias as $media): ?>
        <?= $media->render() ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

<?= $contribution->displayValues() ?>

<?php if (!$embedMedia && $medias): ?>
<div class="media-list">
    <?php foreach ($medias as $media): ?>
        <?= $media->linkPretty() ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if (!$contribution->isSubmitted()): ?>
<ul class="actions" data-message-remove-contribution="<?= $escapeAttr($translate('Are you sure to remove this contribution?')) ?>">
    <?php if ($contribution->userIsAllowed('update')): ?>
    <li><a class="o-icon-edit button edit-button edit-contribution" href="<?= $escapeAttr($contribution->url('edit')) ?>"><?= $escape($translate('Edit')) ?></a></li>
    <?php endif; ?>
    <li><a class="o-icon-submit button submit-button submit-contribution" href="<?= $escapeAttr($contribution->url('submit')) ?>"><?= $escape($translate('Submit')) ?></a></li>
    <?php if ($contribution->userIsAllowed('delete')): ?>
    <li><a class="o-icon-delete button delete-button remove-contribution" data-contribution-id="<?= $contribution->id() ?>" href="#"><?= $escape($translate('Delete')) ?></a></li>
    <?php endif; ?>
</ul>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
