<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Api\Representation\TokenRepresentation[] $tokens
 * @var string $siteSlug
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<?php if (empty($tokens)): ?>

    <div class="no-resources">
        <p><?= $translate('There are no tokens for this resource.') ?></p>
    </div>

<?php else: ?>

<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<div class="contribution contribution-token">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Token') ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($tokens as $token): ?>
        <tr>
            <td>
                <span class="contribution-token"><?= $token->siteUrl($siteSlug, true) ?></span>
                <?php if ($email = $token->email()): ?>
                <span class="contribution-email"><?= $hyperlink($email, 'mailto:' . $email) ?></span>
                <?php else: ?>
                <span class="contribution-email"><?= $translate('[no email]') ?></span>
                <?php endif; ?>
                <?php if ($token->isExpired()): ?>
                <span class="single actions no-action o-icon-expired-token" aria-label="<?= $escape($translate('Expired token')) ?>"></span>
                <?php else: ?>
                <div class="actions">
                    <?php if ($editRight): ?>
                    <button type="button"
                        class="single-action jsend-action expire-token"
                        data-url="<?= $escape($token->adminUrl('expire-token')) ?>"
                        aria-label="<?= $v = $escapeAttr($translate('Expire token')) ?>"
                        title="<?= $v ?>"><span class="fas o-icon-expire-token"></span></button>
                    <?php else: ?>
                    <span class="no-action o-icon-expire-token" aria-label="<?= $escape($translate('Unused token')) ?>"></span>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
            </td>
        </tr>
       <?php endforeach; ?>
   </tbody>
</table>
</div>

<?php endif; ?>
