<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Contribute\Form\ContributeForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation[] $contributions
 * @var \Contribute\Api\Representation\TokenRepresentation[] $unusedTokens
 * @var string $siteSlug
 *
 * For loop:
 * @var \Omeka\View\Helper\Api $api
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Omeka\View\Helper\Hyperlink $hyperlink
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 *
 * @var \Contribute\Api\Representation\ContributionRepresentation $contribution
 * @var bool $editRight
 * @var string $labelInfo
 * @var array $values
 * @var bool $isSubProposal
 * @var array $proposal
 */

/** @var \Omeka\Api\Representation\ResourceTemplateRepresentation $resourceTemplate */
$resourceTemplate = $proposal['template'] ?? null;
// Clean data for the special keys.
unset($proposal['template'], $proposal['media']);
?>

<?php if ($isSubProposal): ?>
<div class="proposal-media">
    <h4><?= sprintf($translate('Media %s'), $this->partialLoop()->getPartialCounter()) ?></h4>
<?php endif; ?>

<div class="property">
    <h4><?= $escape($translate('Resource template')) ?></h4>
    <div class="values">
        <div>
            <div>
                <span class="resource-template"><?= $escape($resourceTemplate ? $resourceTemplate->label() : $translate('No resource template')) ?></span>
            </div>
        </div>
    </div>
</div>
<?php foreach ($proposal as $term => $propositions):
    if (isset($values[$term])):
        $propertyData = $values[$term];
    elseif ($term === 'file'):
        $propertyData = [
            'property' => null,
            'alternate_label' => $translate('File'),
            'alternate_comment' => null,
            'values' => [],
        ];
    else:
        $property = $api->searchOne('properties', ['term' => $term])->getContent();
        // In the case the property was removed after the contribute.
        if (empty($property)) continue;
        $propertyData = [
            'property' => $property,
            'alternate_label' => null,
            'alternate_comment' => null,
            'values' => [],
        ];
    endif;
?>
    <div class="property">
        <h4>
            <?= $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())) ?>
            <?php if (!isset($propertyData['property'])):?>
            <?php // Nothing to do (file). ?>
            <?php elseif ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </h4>
        <div class="values">

        <?php foreach ($propositions as $key => $proposition):
            // TODO Manage all types.
            if (array_key_exists('@uri', $proposition['original'])) {
                $type = 'uri';
            } elseif (array_key_exists('@resource', $proposition['original'])) {
                $type = 'resource';
            } else {
                $type = 'literal';
            }
            switch ($type):
            case 'resource':
                $original = $proposition['original']['@resource'];
                $proposed = $proposition['proposed']['@resource'];
                $isValidated = $proposition['validated'];
                $process = $proposition['process'];

                try {
                    /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $originalResource */
                    $originalResource = $api->read('resources', ['id' => $original])->getContent();
                } catch (\Omeka\Api\Exception\NotFoundException $e) {
                    $originalResource = null;
                }
                try {
                    /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $proposedResource */
                    $proposedResource = $api->read('resources', ['id' => $proposed])->getContent();
                } catch (\Omeka\Api\Exception\NotFoundException $e) {
                    $proposedResource = null;
                }

                $class = ['value'];
                if ($isValidated) $class[] = 'validated-value';
                ?>
                <div>
                    <?php if ($process === 'remove'): ?>
                    <div class="<?= implode(' ', $class) ?> <?= $originalResource ? $originalResource->resourceName() : '' ?>">
                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="remove-value"><?= $originalResource->linkPretty() ?></span>
                    </div>
                    <?php else: ?>
                        <?php if ($original): ?>
                    <div class="<?= implode(' ', $class) ?> <?= $originalResource ? $originalResource->resourceName() : '' ?>">
                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="original-value"><?= $originalResource->linkPretty() ?></span>
                    </div>
                        <?php endif; ?>
                    <div class="<?= implode(' ', $class) ?> <?= $proposedResource ? $proposedResource->resourceName() : '' ?>">
                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="<?= $process ?>-value"><?= $proposedResource->linkPretty() ?></span>
                    </div>
                    <?php endif; ?>

                    <?php if ($contribution->isPatch()): // Only patchs should be validated individually. ?>
                    <span class="single actions">
                    <?php if ($isValidated): ?>
                        <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                    <?php elseif ($process === 'keep'): ?>
                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                    <?php elseif (!$editRight): ?>
                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                    <?php else: ?>
                        <a href="#"
                            class="validate-value o-icon-validate-value"
                            data-validate-value-url="<?= $escapeAttr($contribution->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                            data-status="validate-value"
                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                            title="<?= $txt ?>"></a>
                    <?php endif; ?>
                    </span>
                    <?php endif; ?>
                </div>
                 <?php
                break;

            case 'uri':
                $original_uri = $proposition['original']['@uri'];
                $proposed_uri = $proposition['proposed']['@uri'];
                $original_label = $proposition['original']['@label'];
                $proposed_label = $proposition['proposed']['@label'];

                $isValidated = $proposition['validated'];
                $process = $proposition['process'];

                $class = ['value'];
                if ($isValidated) $class[] = 'validated-value';
                $language = $proposition['value'] ? $proposition['value']->lang() : null;
                ?>
                <div class="<?= implode(' ', $class) ?>" lang="<?= $escapeAttr($language) ?>">
                    <?php if ($language): ?>
                    <span class="language"><?= $escape($language) ?></span>
                    <?php endif; ?>

                    <?php if ($process === 'remove'): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                    <?php else: ?>
                        <?php if ($original_label): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original_uri) ?></span>
                    <br/>
                        <?php endif; ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed_uri) ?></span>
                    <?php endif; ?>

                    <?php if ($contribution->isPatch()): // Only patchs should be validated individually. ?>
                    <span class="single actions">
                    <?php if ($isValidated): ?>
                        <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                    <?php elseif ($process === 'keep'): ?>
                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                    <?php elseif (!$editRight): ?>
                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                    <?php else: ?>
                        <a href="#"
                            class="validate-value o-icon-validate-value"
                            data-validate-value-url="<?= $escapeAttr($contribution->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                            data-status="validate-value"
                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                            title="<?= $txt ?>"></a>
                    <?php endif; ?>
                    </span>
                    <?php endif; ?>
                </div>
                <?php
                break;

            case 'literal':
            default:
                $original = $proposition['original']['@value'];
                $proposed = $proposition['proposed']['@value'];
                $isValidated = $proposition['validated'];
                $process = $proposition['process'];

                $class = ['value'];
                if ($isValidated) $class[] = 'validated-value';
                $language = $proposition['value'] ? $proposition['value']->lang() : null;
                ?>
                <div class="<?= implode(' ', $class) ?>" lang="<?= $escapeAttr($language) ?>">
                    <?php if ($language): ?>
                    <span class="language"><?= $escape($language) ?></span>
                    <?php endif; ?>

                    <?php if ($process === 'remove'): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original) ?></span>
                    <?php else: ?>
                        <?php if ($original): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original) ?></span>
                    <br/>
                        <?php endif; ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed) ?></span>
                    <?php endif; ?>

                    <?php if ($contribution->isPatch()): // Only patchs should be validated individually. ?>
                    <span class="single actions">
                    <?php if ($isValidated): ?>
                        <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                    <?php elseif ($process === 'keep'): ?>
                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                    <?php elseif (!$editRight): ?>
                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                    <?php else: ?>
                        <a href="#"
                            class="validate-value o-icon-validate-value"
                            data-validate-value-url="<?= $escapeAttr($contribution->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                            data-status="validate-value"
                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                            title="<?= $txt ?>"></a>
                    <?php endif; ?>
                    </span>
                    <?php endif; ?>
                </div>
                 <?php
                break;
            endswitch;
        endforeach;
        ?>
        </div>
    </div>
<?php endforeach; ?>

<?php if ($isSubProposal): ?>
</div>
<?php endif; ?>
