<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Correction\Api\Representation\CorrectionRepresentation[] $corrections
 * @var \Correction\Api\Representation\TokenRepresentation[] $unusedTokens
 * @var string $siteSlug
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$api = $this->plugin('api');

$labelInfo = $this->setting('property_label_information');

$values = $resource->values();
?>
<div class="corrections">
    <?php $totalTokens = $api->search('correction_tokens', ['resource_id' => $resource->id()])->getTotalResults(); ?>
    <?php if (empty($totalTokens)): ?>
        <?php if (!$this->setting('correction_without_token')): ?>
    <div class="no-resources no-tokens">
        <p><?= $translate('There are no tokens for this resource.') ?></p>
    </div>
        <?php endif; ?>
    <?php else: ?>
    <?php $totalExpiredTokens = $api
        ->search(
            'correction_tokens',
            ['resource_id' => $resource->id(), 'datetime' => [['field' => 'expire', 'type' => 'lt', 'value' => date('Y-m-d H:i:s')]]]
        )
        ->getTotalResults(); ?>
    <div class="correction-token">
        <p><?= sprintf($translate('There are %d tokens for this resource (%d expired).'), $totalTokens, $totalExpiredTokens) ?></p>
        <?php if (($totalTokens - $totalExpiredTokens) && $this->userIsAllowed('Correction\Controller\Admin\Correction', 'expire-tokens')): ?>
        <?= $hyperlink($translate('Expire all tokens'), $this->url('admin/correction/id', ['action' => 'expire-tokens', 'id' => $resource->id()]), ['class' => 'button']) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>

<?php if (empty($corrections)): ?>
    <div class="no-resources no-corrections">
        <p><?= $translate('There are no corrections for this resource.') ?></p>
    </div>
<?php else: ?>
<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<?php foreach ($corrections as $correction): ?>
<?php $token = $correction->token(); ?>
<div class="correction">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Correction') ?>
                <?php /*
                <span class="correction-id">#<?= $correction->id() ?></span>
                */ ?>
                <?php if ($email = $correction->email()): ?>
                <span class="correction-email"><?= $hyperlink($email, 'mailto:' . $email) ?></span>
                <?php endif; ?>
                <span class="correction-date"><?= $this->i18n()->dateFormat($correction->created(), 'medium', 'medium') ?></span>
                <?php if ($correction->created() != $correction->modified()): // Don't use !==. ?>
                <span class="correction-date-modified"><?= $translate('(modified)') ?></span>
                <?php endif; ?>
                <?php if ($token): ?>
                <span> / </span>
                <span class="correction-token"><?= $hyperlink($token->token(), $token->siteUrl($siteSlug, true)) ?></span>
                <?php endif; ?>
                <?php if ($editRight): ?>
                <?php // TODO Check if all values are the same to change the default icon to "validated". ?>
                <span class="single actions"><a href="#"
                    class="validate o-icon-validate"
                    data-validate-url="<?= $escape($correction->url('validate')) ?>"
                    data-status="validate"
                    aria-label="<?= $escape($translate('Validate all values')) ?>"
                    title="<?= $escape($translate('Validate all values')) ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $correction->reviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($correction->url('toggle-status')) ?>"
                    data-status="<?= $correction->reviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>
                <?php if ($token && $token->isExpired()): ?>
                <span class="single no-action o-icon-expired-token" aria-label="<?= $escape($translate('Expired token')) ?>"></span>
                <?php elseif ($token): ?>
                <span class="single single-action"><a href="#"
                    class="expire-token o-icon-expire-token"
                    data-expire-token-url="<?= $escape($correction->url('expire-token')) ?>"
                    aria-label="<?= $escape($translate('Expire token')) ?>"
                    title="<?= $escape($translate('Expire token')) ?>"></a></span>
                <?php endif; ?>
                <?php else: ?>
                <span class="no-action o-icon-<?= $correction->reviewed() ? 'reviewed' : 'unreviewed' ?>"></span>
                <?php endif; ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="correction-value">
            <td>

<?php $proposal = $correction->proposalCheck(); ?>
<?php foreach ($proposal as $term => $propositions):
    if (isset($values[$term])):
        $propertyData = $values[$term];
    else:
        $property = $api->searchOne('properties', ['term' => $term])->getContent();
        // In the case the property was removed after the correction.
        if (empty($property)) continue;
        $propertyData = [
            'property' => $property,
            'alternate_label' => null,
            'alternate_comment' => null,
            'values' => [],
        ];
    endif;
?>
    <div class="property">
        <h4>
            <?= $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())) ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </h4>
        <div class="values">

        <?php foreach ($propositions as $key => $proposition):
            // TODO Manage all types.
            $type = 'literal';
            if (array_key_exists('@uri', $proposition['original'])) $type = 'uri';
            switch ($type):
            case 'uri':
                $original_uri = $proposition['original']['@uri'];
                $proposed_uri = $proposition['proposed']['@uri'];
                $original_label = $proposition['original']['@label'];
                $proposed_label = $proposition['proposed']['@label'];

                $isValidated = $proposition['validated'];
                $process = $proposition['process'];

                $class = ['value'];
                if ($isValidated) $class[] = 'validated-value';
                $language = $proposition['value'] ? $escape($proposition['value']->lang()) : null;
                ?>
                <div class="<?= implode(' ', $class); ?>" lang="<?= $escape($language) ?>">
                    <?php if ($language): ?>
                    <span class="language"><?= $language ?></span>
                    <?php endif; ?>

                    <?php if ($process === 'remove'): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                    <?php else: ?>
                        <?php if ($original_label): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="original-value"><?= $escape($original_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="original-value"><?= $escape($original_uri) ?></span>
                    <br/>
                        <?php endif; ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="<?= $process; ?>-value"><?= $escape($proposed_label) ?></span><span>:</span>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="<?= $process; ?>-value"><?= $escape($proposed_uri) ?></span>
                    <?php endif; ?>

                    <span class="single actions">
                    <?php if ($isValidated): ?>
                        <span class="no-action o-icon-validated-value" aria-label="<?= $escape($translate('Validated')) ?>"></span>
                    <?php elseif ($process === 'keep'): ?>
                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escape($translate('Not validable')) ?>"></span>
                    <?php elseif (!$editRight): ?>
                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escape($translate('No right to write')) ?>"></span>
                    <?php else: ?>
                        <a href="#"
                            class="validate-value o-icon-validate-value"
                            data-validate-value-url="<?= $escape($correction->url('validate-value') . "?term=$term&key=$key") ?>"
                            data-status="validate-value"
                            aria-label="<?= $txt = $escape(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                            title="<?= $txt ?>"></a>
                    <?php endif; ?>
                    </span>
                </div>
                <?php
                break;

            case 'literal':
            default:
                $original = $proposition['original']['@value'];
                $proposed = $proposition['proposed']['@value'];
                $isValidated = $proposition['validated'];
                $process = $proposition['process'];

                $class = ['value'];
                if ($isValidated) $class[] = 'validated-value';
                $language = $proposition['value'] ? $escape($proposition['value']->lang()) : null;
                ?>
                <div class="<?= implode(' ', $class); ?>" lang="<?= $escape($language) ?>">
                    <?php if ($language): ?>
                    <span class="language"><?= $language ?></span>
                    <?php endif; ?>

                    <?php if ($process === 'remove'): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?= $escape($original) ?></span>
                    <?php else: ?>
                        <?php if ($original): ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="original-value"><?= $escape($original) ?></span>
                    <br/>
                        <?php endif; ?>
                    <span data-name="<?= $term . '[' . $key . '][@value]'; ?>" class="<?= $process; ?>-value"><?= $escape($proposed) ?></span>
                    <?php endif; ?>

                    <span class="single actions">
                    <?php if ($isValidated): ?>
                        <span class="no-action o-icon-validated-value" aria-label="<?= $escape($translate('Validated')) ?>"></span>
                    <?php elseif ($process === 'keep'): ?>
                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escape($translate('Not validable')) ?>"></span>
                    <?php elseif (!$editRight): ?>
                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escape($translate('No right to write')) ?>"></span>
                    <?php else: ?>
                        <a href="#"
                            class="validate-value o-icon-validate-value"
                            data-validate-value-url="<?= $escape($correction->url('validate-value') . "?term=$term&key=$key") ?>"
                            data-status="validate-value"
                            aria-label="<?= $txt = $escape(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                            title="<?= $txt ?>"></a>
                    <?php endif; ?>
                    </span>
                </div>
                 <?php
                break;
            endswitch;
        endforeach;
        ?>
        </div>
    </div>
<?php endforeach; ?>

            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>

<?php if ($unusedTokens): ?>
<h4><?= $translate('Unused tokens') ?></h4>
<?= $this->partial('common/admin/correction-token-list', [
    'resource' => $resource,
    'tokens' => $unusedTokens,
    'siteSlug' => $siteSlug,
]) ?>
<?php endif; ?>

</div>
