<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Correction\Api\Representation\CorrectionRepresentation[] $corrections
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$api = $this->plugin('api');

$labelInfo = $this->setting('property_label_information');

$values = $resource->values();
?>
<div class="corrections">
    <?php $totalTokens = $api->search('correction_tokens', ['resource_id' => $resource->id()])->getTotalResults(); ?>
    <?php if (empty($totalTokens)): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no tokens for this resource.'); ?></p>
    </div>
    <?php else: ?>
    <?php $totalExpiredTokens = $api
        ->search(
            'correction_tokens',
            ['resource_id' => $resource->id(), 'datetime' => [['field' => 'expire', 'type' => 'lt', 'value' => date('Y-m-d H:i:s')]]]
        )
        ->getTotalResults(); ?>
    <div class="correction-token">
        <p><?php echo sprintf($translate('There are %d tokens for this resource (%d expired).'), $totalTokens, $totalExpiredTokens); ?></p>
        <?php if (($totalTokens - $totalExpiredTokens) && $this->userIsAllowed('Correction\Controller\Admin\Correction', 'expire-tokens')): ?>
        <?php echo $this->hyperlink($translate('Expire all tokens'), $this->url('admin/correction/id', ['action' => 'expire-tokens', 'id' => $resource->id()]), ['class' => 'button']); ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php if (empty($corrections)): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no corrections for this resource.'); ?></p>
    </div>
<?php else: ?>
<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<?php foreach ($corrections as $correction): ?>
<div class="correction">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?php echo $translate('Correction'); ?>
                <?php /*
                <span class="correction-id">#<?php echo $correction->id(); ?></span>
                */ ?>
                <?php if ($email = $correction->email()): ?>
                <span class="correction-email"><?php echo $this->hyperlink($email, 'mailto:' . $email); ?></span>
                <?php endif; ?>
                <?php // TODO Correction date is not clear: use the date of the token when modified? ?>
                <span class="correction-date"><?php echo $escape($correction->created()->format('Y-m-d H:i:s')); ?></span>
                <?php if ($editRight): ?>
                <?php // TODO Check if all values are the same to change the default icon to "validated". ?>
                <span class="single actions"><a href="#"
                    class="validate o-icon-validate"
                    data-validate-url="<?php echo $escape($correction->url('validate')); ?>"
                    aria-label="<?php echo $escape($translate('Validate all values')); ?>"
                    title="<?php echo $escape($translate('Validate all values')); ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?php echo $correction->reviewed() ? 'reviewed' : 'unreviewed'; ?>"
                    data-status-toggle-url="<?php echo $escape($correction->url('toggle-status')); ?>"
                    data-status="<?php echo $correction->reviewed() ? 'reviewed' : 'unreviewed'; ?>"
                    aria-label="<?php echo $escape($translate('Toggle status reviewed/unreviewed')); ?>"
                    title="<?php echo $escape($translate('Toggle status reviewed/unreviewed')); ?>"></a></span>
                <?php else: ?>
                <span class="no-action o-icon-<?php echo $correction->reviewed() ? 'reviewed' : 'unreviewed'; ?>"></span>
                <?php endif; ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="correction-value">
            <td>

<?php $proposal = $correction->proposalCheck(); ?>
<?php foreach ($proposal as $term => $propositions):
    if (isset($values[$term])):
        $propertyData = $values[$term];
    else:
        $property = $api->searchOne('properties', ['term' => $term])->getContent();
        // In the case the property was removed after the correction.
        if (empty($property)) continue;
        $propertyData = [
            'property' => $property,
            'alternate_label' => null,
            'alternate_comment' => null,
            'values' => [],
        ];
    endif;
?>
    <div class="property">
        <h4>
            <?php echo $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())); ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
            <?php endif; ?>
        </h4>
        <div class="values">
        <?php foreach ($propositions as $key => $proposition): ?>
            <?php
            $original = $proposition['original']['@value'];
            $proposed = $proposition['proposed']['@value'];
            $isValidated = $proposition['validated'];
            $process = $proposition['process'];

            $class = ['value'];
            if ($isValidated) $class[] = 'validated-value';
            $language = $proposition['value'] ? $escape($proposition['value']->lang()) : null;
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($language); ?>">
                <?php if ($language): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>

                <?php if ($process === 'remove'): ?>
                <span data-name="<?php echo $term . '[' . $key . '][@value]'; ?>" class="remove-value"><?php echo $escape($original); ?></span>
                <?php else: ?>
                <?php if ($original): ?>
                <span data-name="<?php echo $term . '[' . $key . '][@value]'; ?>" class="original-value"><?php echo $escape($original); ?></span>
                <br/>
                <?php endif; ?>
                <span data-name="<?php echo $term . '[' . $key . '][@value]'; ?>" class="<?php echo $process; ?>-value"><?php echo $escape($proposed); ?></span>
                <?php endif; ?>

                <span class="single actions">
                <?php if ($isValidated): ?>
                    <span class="no-action o-icon-validated-value" aria-label="<?php echo $escape($translate('Validated')); ?>"></span>
                <?php elseif ($process === 'keep'): ?>
                    <span class="no-action o-icon-not-validable-value" aria-label="<?php echo $escape($translate('Not validable')); ?>"></span>
                <?php elseif (!$editRight): ?>
                    <span class="no-action o-icon-validate-value no-right" aria-label="<?php echo $escape($translate('No right to write')); ?>"></span>
                <?php else: ?>
                    <a href="#"
                        class="validate-value o-icon-validate-value"
                        data-validate-value-url="<?php echo $escape($correction->url('validate-value') . "?key=$key"); ?>"
                        aria-label="<?php echo $txt = $escape(sprintf($translate('Validate this value (%s)'), $translate($process))); ?>"
                        title="<?php echo $txt; ?>"></a>
                <?php endif; ?>
                </span>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>

            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>
</div>
