<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Correction\Api\Representation\CorrectionRepresentation[] $corrections
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$labelInfo = $this->setting('property_label_information');
$corrigible = $this->setting('correction_properties', []);
?>

<div class="corrections">
<?php if (empty($corrections)): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no corrections for this resource.'); ?></p>
    </div>
<?php else: ?>
<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<?php foreach ($corrections as $correction): ?>
<div class="correction">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?php echo $translate('Correction'); ?>
                <?php /*
                <span class="correction-id">#<?php echo $correction->id(); ?></span>
                */ ?>
                <?php if ($email = $correction->email()): ?>
                <span class="correction-email"><?php echo $this->hyperlink($email, 'mailto:' . $email); ?></span>
                <?php endif; ?>
                <?php // TODO Correction date is not clear: use the date of the token when modified? ?>
                <span class="correction-date"><?php $date = $correction->created(); echo $escape($this->i18n()->dateFormat($date)); ?></span>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="correction-value">
            <td>

<?php // List all corrigible values (set and different from the current values). ?>
<?php // TODO Factorize with public form? ?>
<?php foreach ($resource->values() as $term => $propertyData): ?>
    <?php $isCorrigible = empty($corrigible) || in_array($term, $corrigible); ?>
    <?php if (!$isCorrigible) continue; ?>
    <div class="property">
        <h4>
            <?php echo $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())); ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
            <?php endif; ?>
        </h4>
        <div class="values">
        <?php /** @var \Omeka\Api\Representation\ValueRepresentation $value */ ?>
        <?php foreach ($propertyData['values'] as $key => $value):
            // TODO Manage all types of data, in particular custom vocab and value suggest.
            if ($value->type() !== 'literal') continue;
            // List only modified values.
            $proposedValue = $correction->proposedValue($term, $key);
            if (is_null($proposedValue)) continue;

            $class = ['value'];
            if ('resource' == $value->type()) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $value->type()) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <div data-name="<?php echo $term . '[' . $key . '][@value]'; ?>"><?php echo $escape($proposedValue); ?></div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>

            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>
</div>
