<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$setting = $plugins->get('setting');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$canContribute = $plugins->get('canContribute');
?>

<ul>
    <li>
        <?= $hyperlink(
            $translate('See contributions'), // @translate
            $url('site/guest/contribution', [], true)
        ) ?>
    </li>
    <?php if ($canContribute): ?>
    <li>
        <?= $hyperlink(
            $translate('Add a new record'),
            $url('site/guest/contribution', ['action' => 'add'], true))
        ?>
    </li>
    <?php endif; ?>
</ul>
