<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$translate = $this->plugin('translate');
$url = $this->plugin('url');
$hyperlink = $this->plugin('hyperlink');
?>

<ul>
    <li>
        <?= $hyperlink(
            $translate('See contributions'), // @translate
            $url('site/guest/contribution', [], true)
        ) ?>
    </li>
    <?php if (in_array($this->setting('contribute_mode'), ['user', 'open'])): ?>
    <li>
        <?= $hyperlink($translate('Add a new record'), $url('site/contribute', [], true)) ?>
    </li>
    <?php endif; ?>
</ul>
