<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ResourceForm $form
 * @var array $fields
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('vendor/chosen-js/chosen.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/contribute.css', 'Contribute'));
$this->headScript()
    ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/contribute.js', 'Contribute'), 'text/javascript', ['defer' => 'defer']);

// To check if ValueSuggest is available, just try to get the routed url.
try {
    $proxyUrl = $this->url('site/value-suggest/proxy', [], true);
    $this->headLink()
        ->appendStylesheet($assetUrl('css/value-suggest.css', 'ValueSuggest'));
    $this->headScript()
        ->appendFile($assetUrl('js/jQuery-Autocomplete/1.2.26/jquery.autocomplete.min.js', 'ValueSuggest'), 'text/javascript', ['defer' => 'defer'])
        ->appendFile($assetUrl('js/value-suggest.js', 'ValueSuggest'), 'text/javascript', ['defer' => 'defer'])
        ->appendScript(sprintf(
            'var valueSuggestProxyUrl = "%s";',
            $this->escapeJs($proxyUrl)
        ));
} catch (\Exception $e) {
}

$this->htmlElement('body')->appendAttribute('class', 'edit items' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="container">
    <h2 class="text-primary my-3"><?= $translate('New resource') ?></h2>
    <?= $this->pageTitle(sprintf($translate('Add %s'), $translate($mapLabels['items'])), 3) ?>
    <?= $this->messages() ?>
    <?php $this->trigger('view.edit.before'); ?>
    <?php
    echo $this->partial('contribute/site/contribute/form.phtml', [
        'site' => $site,
        'form' => $form,
        'resource' => null,
        'contribution' => null,
        'fields' => $fields,
        'action' => 'add',
        'submitLabel' => $translate('Submit'),
    ]);
    ?>
</div>

<?php $this->trigger('view.edit.after'); ?>
