<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Correction\Api\Representation\CorrectionRepresentation|null $correction
 * @var array $fields
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/correction.css', 'Correction'));
$this->headScript()
    ->appendFile($assetUrl('js/correction.js', 'Correction'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'edit items' . $this->params()->fromRoute('resource') . ' resource');

$mapLabels = [
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="container">
    <h2 class="text-primary my-3"><?= $resource->displayTitle() ?></h2>
    <?= $this->pageTitle(sprintf($translate('Correct %s'), $translate($mapLabels[$resource->resourceName()])), 3) ?>
    <?= $this->messages() ?>
    <?php $this->trigger('view.edit.before'); ?>
    <?php
    echo $this->partial('correction/site/correction/form.phtml', [
        'form' => $form,
        'resource' => $resource,
        'correction' => $correction,
        'fields' => $fields,
        'action' => 'edit',
        'submitLabel' => $translate('Correct'),
    ]);
    ?>
</div>

<?php $this->trigger('view.edit.after'); ?>
