<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var array $correction
 * @var string $action
 * @var string $submitLabel
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$formElement = $this->plugin('formElement');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();

$labelInfo = $this->setting('property_label_information');
?>

<?php echo $this->form()->openTag($form); ?>

<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php /*
<?php echo $this->partial('common/resource-fields.phtml', [
    'form' => $form,
    'resource' => $item,
]); ?>
*/?>

<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<?php foreach ($resource->values() as $term => $propertyData): ?>
    <div class="property">
        <h4>
            <?php echo $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())); ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
            <?php endif; ?>
        </h4>
        <div class="values">
        <?php /** @var \Omeka\Api\Representation\ValueRepresentation $value */ ?>
        <?php foreach ($propertyData['values'] as $key => $value):
            // TODO Manage all types of data, in particular custom vocab and value suggest.
            if ($value->type() !== 'literal'):
                continue;
            endif;
            $class = ['value'];
            if ('resource' == $value->type()) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $value->type()) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php $val = isset($correction[$term][$key]['@value']) ? $correction[$term][$key]['@value'] : $value; ?>
                <textarea name="<?php echo $term . '[' . $key . '][@value]'; ?>" class="input-value" aria-labelledby="property-<?php echo $propertyData['property']->id(); ?>-label"><?php echo $escape($val); ?></textarea>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>

<?php echo $formElement($form->get('csrf')); ?>

<div id="page-actions">
    <?php // echo $this->cancelButton(); ?>
    <?php echo $this->hyperlink($translate('Go back to resource'), $this->url('site/resource-id', ['controller' => $this->params()->fromRoute('resource'), 'action' => 'show'], true), ['class' => 'button']); ?>
    <button type="submit" name="add-item-submit"><?php echo $escape($submitLabel); ?></button>
</div>

<?php echo $this->form()->closeTag(); ?>

<?php // echo $this->partial('common/resource-form-templates.phtml'); ?>
