<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Form\SendMessageForm $form
 * @var string $heading
 * @var string $html Passed directly from the options.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$form->prepare();
?>

<dialog id="dialog-contribute-send" class="popup popup-dialog dialog-form dialog-send-message dialog-contribute" aria-labelledby="dialog-contribute-send-heading">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button">
                    <span class="dialog-close" aria-hidden="true">🗙</span>
                    <span class="dialog-close-label"><?= $this->translate('Close') ?></span>
                </button>
            </div>
            <div class="dialog-contents">
                <h2 id="dialog-contribute-send-heading" class="dialog-heading"><?= $translate('Send message to contributor') ?></h2>
                <div class="dialog-body">
                    <?= $this->form($form) ?>
                </div>
            </div>
        </div>
    </div>
</dialog>
