<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Contribute\Api\Representation\ContributionRepresentation[] $contributions
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$partial('contribute/site/contribution/asset-include');

$this->htmlElement('body')->appendAttribute('class', 'contribution resource browse');
?>

<?= $this->pageTitle($translate('Contributions'), 2) // @translate ?>

<?php if (count($contributions)): ?>
<h3><?= sprintf($translate('%d contributions'), count($contributions)) // @translate ?></h3>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list contribution-list">
    <?php foreach ($contributions as $contribution): ?>
    <li class="resource contribution">
        <?= sprintf('Contribution #%d (%s)', $contribution->id(), $i18n->dateFormat($contribution->created(), 'medium', 'medium')) ?>
        <h4><?= $contribution->link($contribution->displayTitle()) ?></h4>
        <?php if ($contribution->isSubmitted()): ?>
        <p><?= $escape($translate('Contribution submitted.')) ?></p>
        <?php else: ?>
        <ul class="actions" data-message-remove-contribution="<?= $escapeAttr($translate('Are you sure to remove this contribution?')) ?>">
            <?php if ($contribution->userIsAllowed('update')): ?>
            <li><a class="o-icon-edit button edit-button edit-contribution" href="<?= $escapeAttr($url('site/contribution-id', ['action' => 'edit', 'resource' => 'contribution', 'id' => $contribution->id()], true)) ?>"><?= $escape($translate('Edit')) ?></a></li>
            <?php endif; ?>
            <?php if ($contribution->userIsAllowed('delete')): ?>
            <li><a class="o-icon-delete button delete-button remove-contribution" data-contribution-id="<?= $contribution->id() ?>" href="#"><?= $escape($translate('Delete')) ?></a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<p class="noresults">
    <?= $translate('There are no contributions.') // @translate ?>
</p>
<?php endif; ?>
<div>
    <?= $this->linkContribute() ?>
</div>
